"""initial schema

Revision ID: 0a9985470bd6
Revises: 
Create Date: 2026-08-03 20:22:37.293790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a9985470bd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'admin', 'system', 'bot', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('dividend_placement_curve',
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('pool_fraction', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('placement')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gamertag', sa.String(length=100), nullable=False),
    sa.Column('real_name', sa.String(length=150), nullable=True),
    sa.Column('team', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_shares_outstanding', sa.Integer(), nullable=False),
    sa.Column('ipo_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_gamertag'), 'players', ['gamertag'], unique=True)
    op.create_table('treasury_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auction_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'finalized', name='auction_round_status'), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side'), nullable=False),
    sa.Column('order_kind', sa.Enum('limit', 'quick', name='order_kind'), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'partially_filled', 'filled', 'cancelled', 'rejected', name='order_status'), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(order_kind = 'limit' AND limit_price IS NOT NULL) OR (order_kind = 'quick' AND limit_price IS NULL)", name='ck_order_limit_price_matches_kind'),
    sa.CheckConstraint('filled_quantity >= 0', name='ck_order_filled_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_order_quantity_positive'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_player_id'), 'orders', ['player_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('platform_parameters',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('held_quantity', sa.Integer(), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('held_quantity <= quantity', name='ck_position_held_lte_quantity'),
    sa.CheckConstraint('held_quantity >= 0', name='ck_position_held_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_position_quantity_non_negative'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', name='uq_position_user_player')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_player_id'), 'price_snapshots', ['player_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_recorded_at'), 'price_snapshots', ['recorded_at'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tournament_type', sa.Enum('cash_cup', 'fncs_qualifier', 'fncs_finals', 'global_championship', 'major', 'other', name='tournament_type'), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prize_pool', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'results_pending', 'finalized', name='tournament_status'), nullable=False),
    sa.Column('result_source', sa.Enum('manual', 'csv_import', 'api_import', name='result_source'), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.UUID(), nullable=True),
    sa.Column('seller_user_id', sa.UUID(), nullable=True),
    sa.Column('buy_order_id', sa.UUID(), nullable=True),
    sa.Column('sell_order_id', sa.UUID(), nullable=True),
    sa.Column('buyer_is_bot', sa.Boolean(), nullable=False),
    sa.Column('seller_is_bot', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_trade_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_trade_quantity_positive'),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trades_player_id'), 'trades', ['player_id'], unique=False)
    op.create_table('treasury_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('treasury_instrument_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('active', 'redeemed', name='treasury_holding_status'), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('accrued_interest >= 0', name='ck_treasury_accrued_non_negative'),
    sa.CheckConstraint('principal_amount > 0', name='ck_treasury_principal_positive'),
    sa.ForeignKeyConstraint(['treasury_instrument_id'], ['treasury_instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasury_holdings_status'), 'treasury_holdings', ['status'], unique=False)
    op.create_index(op.f('ix_treasury_holdings_user_id'), 'treasury_holdings', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('held_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash_balance >= 0', name='ck_wallet_cash_non_negative'),
    sa.CheckConstraint('held_balance >= 0', name='ck_wallet_held_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('auction_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_round_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('bid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shares_won', sa.Integer(), nullable=True),
    sa.Column('amount_charged', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bid_amount > 0', name='ck_auction_bid_amount_positive'),
    sa.ForeignKeyConstraint(['auction_round_id'], ['auction_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_round_id', 'user_id', 'player_id', name='uq_auction_bid_round_user_player')
    )
    op.create_index(op.f('ix_auction_bids_auction_round_id'), 'auction_bids', ['auction_round_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_player_id'), 'auction_bids', ['player_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_user_id'), 'auction_bids', ['user_id'], unique=False)
    op.create_table('auction_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_round_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_fee_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_round_id'], ['auction_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_round_id', 'user_id', name='uq_auction_participant_round_user')
    )
    op.create_index(op.f('ix_auction_participants_auction_round_id'), 'auction_participants', ['auction_round_id'], unique=False)
    op.create_index(op.f('ix_auction_participants_user_id'), 'auction_participants', ['user_id'], unique=False)
    op.create_table('dividend_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('total_pool_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shares_outstanding_snapshot', sa.Integer(), nullable=False),
    sa.Column('per_share_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='dividend_payout_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_id', name='uq_dividend_tournament_player')
    )
    op.create_index(op.f('ix_dividend_payouts_player_id'), 'dividend_payouts', ['player_id'], unique=False)
    op.create_index(op.f('ix_dividend_payouts_status'), 'dividend_payouts', ['status'], unique=False)
    op.create_index(op.f('ix_dividend_payouts_tournament_id'), 'dividend_payouts', ['tournament_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('deposit', 'withdrawal', 'order_hold', 'order_release', 'trade_debit', 'trade_credit', 'dividend_credit', 'treasury_buy', 'treasury_redeem', 'fee', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    op.create_table('placement_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prize_won', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('eliminations', sa.Integer(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('entered_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('placement > 0', name='ck_placement_positive'),
    sa.ForeignKeyConstraint(['entered_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_id', name='uq_placement_tournament_player')
    )
    op.create_index(op.f('ix_placement_results_player_id'), 'placement_results', ['player_id'], unique=False)
    op.create_index(op.f('ix_placement_results_tournament_id'), 'placement_results', ['tournament_id'], unique=False)
    op.create_table('treasury_accrual_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['treasury_holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasury_accrual_log_holding_id'), 'treasury_accrual_log', ['holding_id'], unique=False)
    op.create_table('dividend_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity_held_snapshot', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['dividend_payouts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id', 'user_id', name='uq_dividend_line_item_payout_user')
    )
    op.create_index(op.f('ix_dividend_line_items_payout_id'), 'dividend_line_items', ['payout_id'], unique=False)
    op.create_index(op.f('ix_dividend_line_items_user_id'), 'dividend_line_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_line_items_user_id'), table_name='dividend_line_items')
    op.drop_index(op.f('ix_dividend_line_items_payout_id'), table_name='dividend_line_items')
    op.drop_table('dividend_line_items')
    op.drop_index(op.f('ix_treasury_accrual_log_holding_id'), table_name='treasury_accrual_log')
    op.drop_table('treasury_accrual_log')
    op.drop_index(op.f('ix_placement_results_tournament_id'), table_name='placement_results')
    op.drop_index(op.f('ix_placement_results_player_id'), table_name='placement_results')
    op.drop_table('placement_results')
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_dividend_payouts_tournament_id'), table_name='dividend_payouts')
    op.drop_index(op.f('ix_dividend_payouts_status'), table_name='dividend_payouts')
    op.drop_index(op.f('ix_dividend_payouts_player_id'), table_name='dividend_payouts')
    op.drop_table('dividend_payouts')
    op.drop_index(op.f('ix_auction_participants_user_id'), table_name='auction_participants')
    op.drop_index(op.f('ix_auction_participants_auction_round_id'), table_name='auction_participants')
    op.drop_table('auction_participants')
    op.drop_index(op.f('ix_auction_bids_user_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_player_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_round_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_treasury_holdings_user_id'), table_name='treasury_holdings')
    op.drop_index(op.f('ix_treasury_holdings_status'), table_name='treasury_holdings')
    op.drop_table('treasury_holdings')
    op.drop_index(op.f('ix_trades_player_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_price_snapshots_recorded_at'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_player_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('positions')
    op.drop_table('platform_parameters')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_player_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('auction_rounds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('treasury_instruments')
    op.drop_index(op.f('ix_players_gamertag'), table_name='players')
    op.drop_table('players')
    op.drop_table('dividend_placement_curve')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
