"""add bot_profiles

Revision ID: f544eefd1096
Revises: 0a9985470bd6
Create Date: 2026-08-04 01:10:26.154722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f544eefd1096'
down_revision = '0a9985470bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('mm_player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_bot_profiles_strategy'), 'bot_profiles', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_profiles_strategy'), table_name='bot_profiles')
    op.drop_table('bot_profiles')
    # ### end Alembic commands ###
