"""
Simulates the "real Fortnite competitive scene" texture the spec asked
for: players genuinely improving/declining over a season, hot streaks and
slumps, team-switch rumors, retirements/rookies, duo changes, meta shifts,
and a community sentiment signal that overreacts to single results and
only partially self-corrects.

Two scores exist per player:
  - skill_rating: the TRUE underlying ability. Drifts slowly. This is what
    actually determines tournament placement (along with `form` and luck).
  - sentiment: what the market/community actually believes right now.
    Trading bots read this, not the hidden true skill (except `smart_money`,
    which explicitly trades the *gap* between them).

Simulated news (spec: "Every tournament: 2-3 significant events" -- duo
changes, retirement, new teammate, roster rumors, performance slump, meta
changes) is generated by `generate_news_events`, called once per
tournament BEFORE placements are drawn (so a slump/duo-change/meta-shift
this function applies can actually affect this tournament's result, not
just next one). Roster rumors are one of the event *types* here rather
than an independent per-player-per-tournament roll, so their frequency is
part of the same "2-3 events" budget as everything else.
"""

import numpy as np
from .config import SimConfig
from .population import make_rookie_player

NEWS_SENTIMENT_DECAY = 0.7   # recent_news_score decays by this factor each tournament


def pre_tournament_update(players, cfg: SimConfig, rng: np.random.Generator):
    """Advance form (streaks), skill drift, decay recent-news score, and
    continue (but do not start) any already-live rumor's countdown."""
    for p in players:
        # ---- hot streak / slump: AR(1), mean-reverts to 0 ----
        p.form = p.form * cfg.form_persistence + rng.normal(0, cfg.form_noise_scale)

        # ---- true skill drift: small mean-reverting random walk ----
        drift = (cfg.skill_mean_reversion * (p.origin_skill - p.skill_rating)
                 + rng.normal(0, cfg.skill_drift_std))
        p.skill_rating = float(np.clip(p.skill_rating + drift, 1.0, cfg.skill_max))

        # ---- recent news score decays toward 0 ----
        p.recent_news_score *= NEWS_SENTIMENT_DECAY

        # ---- rumor lifecycle: only CONTINUE/RESOLVE here; starting a new
        # rumor is one of the news-event types in generate_news_events ----
        if p.rumor_active:
            p.rumor_rounds_left -= 1
            if p.rumor_rounds_left <= 0:
                _resolve_rumor(p, cfg, rng)


def _start_rumor(p, cfg: SimConfig, rng: np.random.Generator):
    p.rumor_active = True
    p.rumor_direction = 1 if rng.random() < 0.5 else -1
    p.rumor_rounds_left = int(rng.integers(cfg.rumor_duration_min, cfg.rumor_duration_max + 1))
    p.rumor_magnitude = float(rng.uniform(cfg.rumor_skill_impact_min, cfg.rumor_skill_impact_max))
    p.last_rumor_confirmed = None


def _resolve_rumor(p, cfg: SimConfig, rng: np.random.Generator):
    confirmed = rng.random() < cfg.rumor_confirm_prob
    if confirmed:
        shift = p.rumor_direction * p.rumor_magnitude
        p.skill_rating = float(np.clip(p.skill_rating + shift, 1.0, cfg.skill_max))
        p.origin_skill = float(np.clip(p.origin_skill + shift * 0.6, 1.0, cfg.skill_max))
    p.last_rumor_confirmed = confirmed
    p.rumor_active = False
    p.rumor_direction = 0
    p.rumor_rounds_left = 0


def update_sentiment(players, noise_by_player: dict, cfg: SimConfig, rng: np.random.Generator):
    """Called right after a tournament's placements are known. Sentiment
    mean-reverts toward true skill, but this tournament's luck (noise) is
    amplified (overreaction_factor > 1) -- exactly the "community
    overexaggerates a single bad/good game" behavior. An active rumor adds
    extra speculative volatility on top."""
    for p in players:
        noise = noise_by_player.get(p.player_id, 0.0)
        p.sentiment = (p.sentiment * (1 - cfg.sentiment_decay_toward_skill)
                       + p.skill_rating * cfg.sentiment_decay_toward_skill)
        p.sentiment += cfg.overreaction_factor * noise
        if p.rumor_active:
            p.sentiment += rng.normal(0, cfg.rumor_sentiment_shock_scale)
        p.sentiment = float(np.clip(p.sentiment, 1.0, cfg.skill_max * 1.5))


# ======================================================================
# Simulated news events
# ======================================================================

def _weighted_choice(rng: np.random.Generator, weights: dict) -> str:
    keys = list(weights.keys())
    probs = np.array(list(weights.values()), dtype=float)
    probs = probs / probs.sum()
    return rng.choice(keys, p=probs)


def generate_news_events(players, players_by_id, cfg: SimConfig, rng: np.random.Generator,
                          tournament_idx: int, used_names: set):
    """Fires 2-3 significant news events for this tournament. Returns a
    list of log dicts (tournament, event_type, player_id, description) for
    reporting. May replace a retiring Player object in-place inside
    `players` / `players_by_id` (same player_id slot, fresh rookie)."""
    n_events = int(rng.integers(cfg.news_events_per_tournament_min,
                                 cfg.news_events_per_tournament_max + 1))
    log = []
    for _ in range(n_events):
        event_type = _weighted_choice(rng, cfg.news_type_weights)
        entry = _fire_event(event_type, players, players_by_id, cfg, rng, tournament_idx, used_names)
        if entry is not None:
            log.append(entry)
    return log


def _fire_event(event_type, players, players_by_id, cfg, rng, tournament_idx, used_names):
    if event_type == "roster_rumor":
        candidates = [p for p in players if not p.rumor_active]
        if not candidates:
            return None
        p = candidates[int(rng.integers(0, len(candidates)))]
        _start_rumor(p, cfg, rng)
        direction = "joining a stronger lineup" if p.rumor_direction > 0 else "leaving/downgrading"
        return {"tournament": tournament_idx, "event_type": "roster_rumor", "player_id": p.player_id,
                "description": f"{p.name}: rumored to be {direction}."}

    if event_type == "retirement":
        weights = np.array([p.retirement_probability for p in players], dtype=float)
        if weights.sum() <= 0:
            return None
        weights = weights / weights.sum()
        idx = rng.choice(len(players), p=weights)
        retiree = players[idx]
        rookie = make_rookie_player(retiree.player_id, cfg, rng, used_names, tournament_idx)
        players[idx] = rookie
        players_by_id[rookie.player_id] = rookie
        return {"tournament": tournament_idx, "event_type": "retirement", "player_id": rookie.player_id,
                "description": f"{retiree.name} retires; {rookie.name} steps into the roster slot."}

    if event_type == "duo_change":
        p = players[int(rng.integers(0, len(players)))]
        sign = 1 if rng.random() < 0.5 else -1
        impact = sign * cfg.duo_change_skill_impact * rng.uniform(0.5, 1.0)
        p.skill_rating = float(np.clip(p.skill_rating + impact, 1.0, cfg.skill_max))
        p.origin_skill = float(np.clip(p.origin_skill + impact * 0.5, 1.0, cfg.skill_max))
        p.sentiment = float(np.clip(p.sentiment + impact * 1.5, 1.0, cfg.skill_max * 1.5))
        p.recent_news_score += impact
        verb = "a stronger" if sign > 0 else "a weaker"
        return {"tournament": tournament_idx, "event_type": "duo_change", "player_id": p.player_id,
                "description": f"{p.name} switches duo partners, community expects {verb} result."}

    if event_type == "new_teammate":
        p = players[int(rng.integers(0, len(players)))]
        sign = 1 if rng.random() < 0.65 else -1  # new-teammate news skews optimistic
        impact = sign * cfg.duo_change_skill_impact * 0.6 * rng.uniform(0.5, 1.0)
        p.sentiment = float(np.clip(p.sentiment + impact * 2.0, 1.0, cfg.skill_max * 1.5))
        p.recent_news_score += impact
        tone = "upgrade" if sign > 0 else "downgrade"
        return {"tournament": tournament_idx, "event_type": "new_teammate", "player_id": p.player_id,
                "description": f"{p.name} picks up a new teammate; community reads it as a {tone}."}

    if event_type == "performance_slump":
        p = players[int(rng.integers(0, len(players)))]
        p.form = cfg.slump_form_shock * rng.uniform(0.6, 1.0)
        p.recent_news_score -= abs(cfg.slump_form_shock) * 0.3
        return {"tournament": tournament_idx, "event_type": "performance_slump", "player_id": p.player_id,
                "description": f"{p.name} is publicly struggling -- a visible slump going into this event."}

    if event_type == "meta_change":
        sign = 1 if rng.random() < 0.5 else -1
        median_vol = float(np.median([p.volatility_rating for p in players]))
        affected = [p for p in players if (p.volatility_rating >= median_vol) == (sign > 0)]
        rng.shuffle(affected)
        affected = affected[: max(1, len(affected) // 3)]
        for p in affected:
            impact = sign * cfg.meta_change_skill_impact * rng.uniform(0.5, 1.0)
            p.skill_rating = float(np.clip(p.skill_rating + impact, 1.0, cfg.skill_max))
            p.recent_news_score += impact
        style = "aggressive, high-variance" if sign > 0 else "consistent, low-variance"
        return {"tournament": tournament_idx, "event_type": "meta_change", "player_id": None,
                "description": f"A meta shift favors {style} playstyles ({len(affected)} players affected)."}

    return None
